name: Linting and Testing

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:

jobs:
  linting:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Prepare for linting
        run: pnpm prepare

      - name: Run ESLint
        run: pnpm lint

  building:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/**'
          cache: 'pnpm'
      
      - name: Install pnpm packages
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm build
